#super permissins required
sudo: required
services:
  - docker

#Make sure commands are built to run our docker image
before_install:
  - docker build -t jeremybamaddox/docker-react -f Dockerfile.dev .

#tell travis how to run our test suite
##will watch for status codes
script:
  - docker run -e CI=true jeremybamaddox/docker-react npm run test -- --coverage

#deployment section
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-162194444266"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY